name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false
      merge_target:
        description: Target branch to merge into. Uses the default branch as a fallback (optional)
        required: false

jobs:
  prepare_framework:
    runs-on: macos-13-xlarge
    name: 'Create XCFramework'
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache xcframework
        id: framework-cache
        uses: actions/cache@v4
        with:
          path: |
            Carthage/Sentry.xcframework.zip
            Carthage/SentrySwiftUI.xcframework.zip
          key: sentry-xcframeworks-key-${{ github.event.inputs.version }}
    
      - name: 'Generate XCFramework'
        run: |
            ./scripts/ci-select-xcode.sh 15.2
            make build-xcframework
      
      - name: 'Update Package.swift'
        run: ./scripts/update-package-sha.sh "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" ${{ github.workspace }}/Carthage/Sentry.xcframework.zip

  job_release:
    runs-on: ubuntu-latest
    name: 'Release a new version'
    needs: prepare_framework
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          fetch-depth: 0

      - name: Prepare release
        uses: getsentry/action-prepare-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        with:
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
          merge_target: ${{ github.event.inputs.merge_target }}
